baseURL = 'https://ssyoung26.github.io/sunbew/'
languageCode = 'en-us'
title = "Sonny Young"
theme = 'shibui'
publishDir = 'public'
relativeURLs = false
canonifyURLs = true

[params.profile]
  description = "Ph.D. Student"
  affiliation = "MIT"
  author = "Sonny Young"
  email = "ssyoung [at] mit [dot] edu"
  location = "Cambridge, MA"
  headshot = "/images/headshot.png"
  enableEmoji = true

  scholar = "Sonny Young"
  github  = "ssyoung26"
  linkedin = "Sonny Young"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
